/* Edit prices here. Amounts are INR per person for a minimum of four guests in a sedan.
   Use null when a confirmed rate is unavailable; the card will invite an exact quote. */
window.GREEN_EAGLE_RATES = {
  ooty: [{duration:'1 Day',price:1500},{duration:'2 Days / 1 Night',price:1875},{duration:'3 Days / 2 Nights',price:2750},{duration:'4 Days / 3 Nights',price:3500}],
  kodaikanal: [{duration:'1 Day',price:2000},{duration:'2 Days / 1 Night',price:2750},{duration:'3 Days / 2 Nights',price:3375},{duration:'4 Days / 3 Nights',price:4000}],
  valparai: [{duration:'1 Day',price:1750},{duration:'2 Days / 1 Night',price:2125},{duration:'3 Days / 2 Nights',price:2750}],
  madurai: [{duration:'2 Days / 1 Night',price:2375},{duration:'3 Days / 2 Nights',price:null},{duration:'4 Days / 3 Nights',price:5750}],
  rameshwaram: [{duration:'2 Days / 1 Night',price:3625},{duration:'3 Days / 2 Nights',price:4250},{duration:'4 Days / 3 Nights',price:5875}],
  'madurai-rameshwaram': [{duration:'2 Days / 1 Night',price:4625},{duration:'3 Days / 2 Nights',price:6200}],
  munnar: [{duration:'1 Day',price:2125},{duration:'2 Days / 1 Night',price:2625},{duration:'3 Days / 2 Nights',price:3250},{duration:'4 Days / 3 Nights',price:4000}],
  vagamon: [{duration:'2 Days / 1 Night',price:3000},{duration:'3 Days / 2 Nights',price:3750}],
  wayanad: [{duration:'3 Days / 2 Nights',price:3450},{duration:'4 Days / 3 Nights',price:4750},{duration:'5 Days / 4 Nights',price:5750}],
  kanthaloor: [{duration:'2 Days / 1 Night',price:null},{duration:'3 Days / 2 Nights',price:null}],
  alleppey: [{duration:'2 Days / 1 Night',price:3125},{duration:'3 Days / 2 Nights',price:4000}],
  mysore: [{duration:'2 Days / 1 Night',price:2750}],
  coorg: [{duration:'3 Days / 2 Nights',price:3875}],
  chikmagalur: [{duration:'3 Days / 2 Nights',price:4750},{duration:'4 Days / 3 Nights',price:5625}],
  guruvayur: [{duration:'1 Day',price:1625},{duration:'2 Days / 1 Night',price:2250}],
  sabarimala: [{duration:'2 Days / 1 Night',price:3125}],
  coimbatore: [{duration:'1 Day',price:1500},{duration:'2 Days / 1 Night',price:1875}],
  kotagiri: [{duration:'1 Day',price:null},{duration:'2 Days / 1 Night',price:1875},{duration:'3 Days / 2 Nights',price:2750},{duration:'4 Days / 3 Nights',price:3500}],
  marudhamalai: [{duration:'1 Day',price:null},{duration:'2 Days / 1 Night',price:1750}],
  kanyakumari: [{duration:'3 Days / 2 Nights',price:4750},{duration:'4 Days / 3 Nights',price:6750}],
  palani: [{duration:'1 Day',price:1500},{duration:'2 Days / 1 Night',price:null}],
  tiruvannamalai: [{duration:'2 Days / 1 Night',price:null},{duration:'3 Days / 2 Nights',price:4250}],
  thanjavur: [{duration:'2 Days / 1 Night',price:null},{duration:'3 Days / 2 Nights',price:null}],
  trichy: [{duration:'2 Days / 1 Night',price:null},{duration:'3 Days / 2 Nights',price:null}],
  tiruchendur: [{duration:'2 Days / 1 Night',price:3875},{duration:'3 Days / 2 Nights',price:5375}],
  chidambaram: [{duration:'2 Days / 1 Night',price:null},{duration:'3 Days / 2 Nights',price:null}],
  thekkady: [{duration:'2 Days / 1 Night',price:3250},{duration:'3 Days / 2 Nights',price:null}],
  athirapally: [{duration:'1 Day',price:1875},{duration:'2 Days / 1 Night',price:2625},{duration:'3 Days / 2 Nights',price:5250}],
  kochi: [{duration:'1 Day',price:2125},{duration:'2 Days / 1 Night',price:null},{duration:'4 Days / 3 Nights',price:5000}],
  kovalam: [{duration:'3 Days / 2 Nights',price:null},{duration:'4 Days / 3 Nights',price:null}],
  varkala: [{duration:'3 Days / 2 Nights',price:null},{duration:'4 Days / 3 Nights',price:null}],
  udupi: [{duration:'3 Days / 2 Nights',price:5750},{duration:'4 Days / 3 Nights',price:null}],
  bandipur: [{duration:'2 Days / 1 Night',price:2375},{duration:'3 Days / 2 Nights',price:null}],
  nagarhole: [{duration:'3 Days / 2 Nights',price:4375},{duration:'4 Days / 3 Nights',price:null}],
  gokarna: [{duration:'3 Days / 2 Nights',price:null},{duration:'4 Days / 3 Nights',price:null}],
  tirupati: [{duration:'3 Days / 2 Nights',price:null},{duration:'4 Days / 3 Nights',price:null}]
};
